# Generated by Django 4.1.6 on 2023-02-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complate',
            new_name='complete',
        ),
    ]
